### ISSUE TITLE
Allow sending arbitrary patches

### ISSUE THREAD

**Issue by jb55** [fiatjaf/gitstr#1]
You can't seem to add arguments to `git str send`, so I can't include base-commit info which is pretty important when sending patches. So ideally there would be a way to just send the patches directly by referencing a file. since you might want to add annotations and other stuff. When using git-send-email, you would include annotations under the `---` line, but I wonder if we could just use the content field for this.

**Comment by fiatjaf** [comment]
You mean you would like to forward all arguments to `git str send` to `git format-patch`? Or just take a filename? Or both?

I agree the best approach is to add the comments in the patch that goes in `content` like in the git-email flow instead of adding properties to the Nostr event -- if that's what you mean.

**Comment by jb55** [comment]
yeah either or both would be nice.

**Comment by jb55** [comment]
thanks! works

https://njump.me/nevent1qqsdy8ajer303s9p6ncyuk059juec44yeajedy2qtydgqmal546t27spz3mhxue69uhhyetvv9ujuerpd46hxtnfdu5p4yf2

**Comment by fiatjaf** [comment]
`git send-email` and `git format-patch` have a huge amount of options. With I'll get there eventually.
